export const CACHED_DATAFILE_LOADED = 'CACHED_DATAFILE_LOADED'
export const DATAFILE_LOADED = 'DATAFILE_LOADED'

export const EXPERIMENT_ACTIVATE_START = 'EXPERIMENT_ACTIVATE_START'
export const EXPERIMENT_ACTIVATE_FINISH = 'EXPERIMENT_ACTIVATE_FINISH'

export const IS_FEATURE_ENABLED_START = 'IS_FEATURE_ENABLED_START'
export const IS_FEATURE_ENABLED_FINISH = 'IS_FEATURE_ENABLED_FINISH'

export const IMPRESSION_EVENT = 'IMPRESSION_EVENT'
export const CONVERSION_EVENT = 'CONVERSION_EVENT'


