name: Javascript

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_markdown_files:
    uses: optimizely/javascript-sdk/.github/workflows/lint_markdown.yml@uzair/gitactions

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Move to package
      run: |
        cd packages/optimizely-sdk
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
    - name: Run linting
      run: |
        npm run lint
    - name: Run linting
      run: |
        npm run lint

  integration_tests:
    uses: optimizely/javascript-sdk/.github/workflows/integration_test.yml@uzair/gitactions
    secrets:
      CI_USER_TOKEN: ${{ secrets.CI_USER_TOKEN }}
      TRAVIS_COM_TOKEN: ${{ secrets.TRAVIS_COM_TOKEN }}

  fullstack_production_suite:
    uses: optimizely/javascript-sdk/.github/workflows/integration_test.yml@uzair/gitactions
    with:
      FULLSTACK_TEST_REPO: ProdTesting
    secrets:
      CI_USER_TOKEN: ${{ secrets.CI_USER_TOKEN }}
      TRAVIS_COM_TOKEN: ${{ secrets.TRAVIS_COM_TOKEN }}

  crossbrowser_and_umd_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Move to package
      run: |
        cd packages/optimizely-sdk
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 8
        cache: 'npm'
    - name: Cross-browser and umd unit tests
      run: |
        npm run test-ci

  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '8', '9', '10', '12', '14' ]
    steps:
    - uses: actions/checkout@v2
    - name: Move to package
      run: |
        cd packages/optimizely-sdk
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install packages
      run: |
        npm install
    - name: Run tests
      run: |
        npm test
    - name: Run coveralls
      run: |
        npm run coveralls
        
  test_sub_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'packages/utils', 'packages/event-processor', 'packages/logging', 'packages/datafile-manager']
    steps:
    - uses: actions/checkout@v2
    - name: Move to package ${{ matrix.package }}
      run: |
        cd ${{ matrix.package }}
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
    - name: Install packages
      run: |
        npm install
    - name: Run tests
      run: |
        npm test
    - name: Run coveralls
      run: |
        npm run coveralls
