name: PR

on:
  push:
    branches: [ master ]
  pull_request:
     types: [opened, edited]

jobs:

  ticket_url_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Jira ticket link
        uses: shaharyar123/ticket-reference-available@master
        with:
          bodyRegex: 'OASIS-(?<ticketNumber>\d+)' 
          bodyURLRegex: 'http(s?):\/\/(optimizely.atlassian.net)(\/browse)\/(OASIS\-)(?<ticketNumber>\d+)'