name: Publish SDK to NPM and GPR

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  publish_to_npm:
    name: Publish to NPM
    uses: ./.github/workflows/common-publish.yml
    with:
      registry-url: 'https://registry.npmjs.org/'
      node-auth-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
      browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

  publish_to_gpr:
    name: Publish to GitHub Package Registry
    uses: ./.github/workflows/common-publish.yml
    with:
      registry-url: 'https://npm.pkg.github.com/'
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
      browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
      browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}