on:
  pull_request:
     types: [opened, edited, reopened, synchronize]

jobs:

  ticket_reference_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Jira ticket reference
        uses: optimizely/github-action-ticket-reference-checker-public@master
        with:
          bodyRegex: 'OASIS-(?<ticketNumber>\d+)' 
